version: '3'

services:
  mage_spark:
    image: mageai/mageai:0.9.22
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPARK_MASTER_HOST=local
    ports:
      - "6789:6789"
      - "4040:4040"
    volumes:
      - .:/home/src
    command: /app/run_app.sh mage start demo_project
