triggers:
- envs: []
  name: runit
  pipeline_uuid: black_meadow
  schedule_interval: null
  schedule_type: api
  settings: {}
  sla: null
  start_time: 2024-04-01 08:21:00
  status: active
  variables: null
